title: EveryDay Libary
email: your-email@example.com
description: 공부한 것들을 차곡차곡 쌓아가는 곳
author: RoadtoS7
baseurl: ""
url: "https://roadtos7.github.io"


# Social Profiles
github_username: RoadtoS7
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

## fonts
google_fonts: "Nanum+Gothic:400,700"
