title: "EveryDay Libary"
email: "your-email@example.com"
description: "공부한 것들을 차곡차곡 쌓아가는 곳"
author: "RoadtoS7"
baseurl: "/"
url: "https://roadtos7.github.io"
encoding: UTF-8

# Comment
repository: "RoadtoS7/roadtos7.github.io"
comments: 
  provider: "utterances"
  utterances:
    theme: "boxy-light"
    issue_term: "pathname"


# Social Profiles
github_username: "RoadtoS7"

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

## fonts
google_fonts: "Nanum+Gothic:400,700"


